#Solios Capbilty:
#One Solios = 4 x 4k@30 transcoding or
#             16 x 2k@30 transcoding or
#             32 x 720p@30 transcoding or
#             96 x 480p@30 transcoding

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: solios-device-plugin-daemonset-480p
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: solios-device-plugin-480p
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      labels:
        name: solios-device-plugin-480p
    spec:
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      containers:
      - image: verisilicon/solios-x-device-plugin:latest
        command: ["solios-x-device-plugin"]
        args: ["-unit", "480p", "-priority", "performance"]
        name: solios-x-device-plugin
        imagePullPolicy: IfNotPresent
        securityContext:
          readOnlyRootFilesystem: true
        volumeMounts:
        - name: devfs
          mountPath: /dev
        - name: sys
          mountPath: /sys
        - name: kubeletsockets
          mountPath: /var/lib/kubelet/device-plugins
      volumes:
      - name: devfs
        hostPath:
          path: /dev
      - name: sys
        hostPath:
          path: /sys
      - name: kubeletsockets
        hostPath:
          path: /var/lib/kubelet/device-plugins
