apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: solios-device-plugin-daemonset-solios
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: solios-device-plugin-solios
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      labels:
        name: solios-device-plugin-solios
    spec:
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      containers:
      - image: verisilicon/solios-x-device-plugin:latest
        command: ["solios-x-device-plugin"]
        args: ["-unit", "solios"]
        name: solios-x-device-plugin
        imagePullPolicy: IfNotPresent
        securityContext:
          readOnlyRootFilesystem: true
        volumeMounts:
        - name: devfs
          mountPath: /dev
        - name: sys
          mountPath: /sys
        - name: kubeletsockets
          mountPath: /var/lib/kubelet/device-plugins
      volumes:
      - name: devfs
        hostPath:
          path: /dev
      - name: sys
        hostPath:
          path: /sys
      - name: kubeletsockets
        hostPath:
          path: /var/lib/kubelet/device-plugins
