apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: solios-test-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: solios-test-pod
  template:
    metadata:
      labels:
        app: solios-test-pod
    spec:
      containers:
      - name: solios-x
        image: verisilicon/solios-x:latest_csd
        ports:
        - containerPort: 80
        volumeMounts:
          - name: sys
            mountPath: /sys
          - name: hugepage
            mountPath: /hugepages
        resources:
          requests:
            verisilicon.com/solios: 1
          limits:
            memory: "512Mi"
            hugepages-2Mi: 1024Mi
            verisilicon.com/solios: 1
      volumes:
      - name: sys
        hostPath:
            path: /sys
      - name: hugepage
        emptyDir:
          medium: HugePages
