# Solios Capbilty:
# 1 x Solios = 4 x 4k@30 transcoding or
#             16 x 2k@30 transcoding or
#             32 x 720p@30 transcoding or
#             96 x 480p@30 transcoding

apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: solios-test-deployment-solios
spec:
  replicas: 2
  selector:
    matchLabels:
      app: solios-test-pod-solios
  template:
    metadata:
      labels:
        app: solios-test-pod-solios
    spec:
      containers:
      - name: solios-x
        image: verisilicon/solios-x:latest
        ports:
        - containerPort: 80
        volumeMounts:
          - name: sys
            mountPath: /sys
          - name: hugepage
            mountPath: /hugepages
        resources:
          requests:
            verisilicon.com/solios: 1
          limits:
            memory: "512Mi"
            hugepages-2Mi: 1024Mi
            verisilicon.com/solios: 1
      volumes:
      - name: sys
        hostPath:
            path: /sys
      - name: hugepage
        emptyDir:
          medium: HugePages
