apiVersion: v1
kind: Pod
metadata:
  name: solios-test-pod-1080p
  labels:
    name: solios-test-pod-1080p
spec:
  containers:
  - name: solios-x
    image: verisilicon/solios-x:latest
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - name: sys
        mountPath: /sys
      - name: hugepage
        mountPath: /hugepages
    resources:
      requests:
        verisilicon.com/solios_1080p: 1
      limits:
        memory: "180Mi"
        hugepages-2Mi: 180Mi
        cpu: 1000m
        verisilicon.com/solios_1080p: 1
    ports:
      - containerPort: 80
    env:
      - name: SOLIOS_POD_IP
        valueFrom:
           fieldRef:
              fieldPath: status.podIP
  volumes:
  - name: sys
    hostPath:
        path: /sys
  - name: hugepage
    emptyDir:
      medium: HugePages
