apiVersion: v1
kind: Pod
metadata:
  name: solios-test-pod
  labels:
    name: solios-test-pod
spec:
  containers:
  - name: solios
    image: verisilicon/solios:0.2
    resources:
      requests:
        memory: "128Mi"
        cpu: "500m"
        verisilicon.com/solios: 1
      limits:
        memory: "128Mi"
        cpu: "500m"
        verisilicon.com/solios: 1
    ports:
      - containerPort: 80
