apiVersion: v1
kind: Pod
metadata:
  name: solios-test-pod
  labels:
    name: solios-test-pod
spec:
  containers:
  - name: solios-x
    image: verisilicon/solios-x:0.3
    volumeMounts:
      - name: dev
        mountPath: /dev
    resources:
      requests:
        memory: "128Mi"
        cpu: "500m"
        verisilicon.com/solios: 1
      limits:
        memory: "128Mi"
        cpu: "500m"
        verisilicon.com/solios: 1
    ports:
      - containerPort: 80
    securityContext:
          privileged: true #Needed for /dev
          capabilities:
            drop: ["ALL"]
  volumes:
  - name: dev
    hostPath:
        path: /dev
