apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: solios-admin-binding
roleRef:
    kind: ClusterRole
    name: cluster-admin
    apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: solios-admin
    namespace: {{ .Values.namespace }}